### ISSUE TITLE
Bot API 2.0

### ISSUE THREAD

**Issue by leandrotoledo** [python-telegram-bot/python-telegram-bot#232]
**Official announcement**: https://core.telegram.org/bots/2-0-intro
**Changelog**: https://core.telegram.org/bots/api-changelog

- [x] New inline keyboards with callback and URL buttons. Added new objects InlineKeyboardMarkup, InlineKeyboardButton and CallbackQuery, added _reply_markup_ fields to all InlineQueryResult objects. Added field _callback_query_ to the Update object, new method answerCallbackQuery.

- [x] Bots can now edit their messages. Added methods editMessageText, editMessageCaption, editMessageReplyMarkup.

- [x] Bots can request location and phone number from the user. The _keyboard_ field in the object ReplyKeyboardMarkup now supports KeyboardButton, a new object that can have the fields _request_location_ and _request_contact_.

- [x] Added support for all content types available on Telegram. 19 types of InlineQueryResult objects are now supported.

- [x] Inline bots can now subsitute all kinds of content with text. Added 4 types of InputMessageContent objects.

- [x] You inline bot can also ask users for permission to use their location. Added the new Botfather command /setinlinegeo, added field _location_ to the InlineQuery object, added fields _location_ and _inline_message_id_ to the ChosenInlineResult object.

- [x] Added an easy way to switch between inline mode and a private chat with the bot – useful for settings, establishing external connections and teaching users how to use your bot in inline mode. Added parameters _switch_pm_text_ and _switch_pm_parameter_ to the method answerInlineQuery.

- [x] Added group administration tools. New methods kickChatMember and unbanChatMember.

- [x] Added fields _venue_, _pinned_message_ and _entities_ to the Message object. Added new objects MessageEntity and Venue, new methods sendVenue and sendContact.

- [x] Renamed the fields _new_chat_participant_ and _left_chat_participant_ of the Message object to _new_chat_member_ and _left_chat_member_.

**Comment by leandrotoledo** [comment]
Some thoughts:

>  Bots can now edit their messages. Added methods editMessageText, editMessageCaption, editMessageReplyMarkup.

- Maybe it's time to add ``disable_web_page_preview`` to ``message`` decorator.

- Although ``*_id``s are not required we have to raise a ``TelegramError`` if none of them are passed or ``chat_id`` without ``message_id`` and vice versa (or simply rely on API error response).

>  Added support for all content types available on Telegram. 19 types of InlineQueryResult objects are now supported.

- Let's move what we have from ``inlinequeryresult.py`` to its own files.


> Inline bots can now subsitute all kinds of content with text. Added 4 types of InputMessageContent objects.

- ``InputTextMessageContent``, ``InputLocationMessageContent``, ``InputVenueMessageContent`` and ``InputContactMessageContent`` extends ``InputMessageContent``, like we do with ``InlineQueryResult`` and ``ReplyMarkup``.

Add tests.

**Comment by leandrotoledo** [comment]
@leandrotoledo As pointed by Jannes we could add an extra backwards compability layer to *_participant args.

**Comment by leandrotoledo** [comment]
Note to self, it's always good **to not** initialize optional arguments at class creation, instead use ``**kwargs``, it's well known Telegram API can change without notice, in that case if a new argument is added it won't break the class.

Good:
```
def __init__(self, id, name, **kwargs):
   ...
   kwargs.get('last_name', '')
   ...

# won't get right arg but doesn't break the class either
User.de_json(id=1, name='Leandro', surname='Souza')
```

Bad:
```
def __init__(self, id, name, last_name=None):

# breaks the class
User.de_json(id=1, name='Leandro', surname='Souza') 
```

**Comment by leandrotoledo** [comment]
Another regression:
- Before: ``ReplyKeyboardMarkup.keyboard(List[List[]])``
- Now: ``ReplyKeyboardMarkup.keyboard(List[List[:class:telegram.KeyboardButton]])``

**Comment by leandrotoledo** [comment]
+ @python-telegram-bot/developers 

If anyone got the cycle, we need to code the new InlineQueryResult* classes, it's not hard - it's just verbose...

Thanks.

**Comment by leandrotoledo** [comment]
Bot 2.0 features are now live on this branch.

```
$ git clone -b bot-api-2.0 --single-branch https://github.com/python-telegram-bot/python-telegram-bot
$ cd python-telegram-bot
$ python setup.py install
```

Missing docstrings and tests, not ready for production.

**Comment by leandrotoledo** [comment]
More args deprecated on ``InlineResult`` and ``InlineQueryResult`` objects:
- message_text
- parse_mode
- disable_web_page_preview

**Comment by leandrotoledo** [comment]
One more, ``InlineQueryResultPhoto.mime_type``

**Comment by ikanez** [comment]
hi. is keyboardbutton supported? i'm trying to extract phone number and location from my user - not sure how to do that at the moment.

**Comment by jh0ker** [comment]
@ikanez Yes. Check out the dispatcher-rework branch, there is an example that uses an inline keyboard in the example folder

**Comment by aryanbaghi** [comment]
In InlineKeyboardButton when I pass `switch_inline_query=''` message did not sent correctly. But when I set at lease one character in it, it's work. According to telegram doc it could be empty.

**Comment by leandrotoledo** [comment]
Hi @aryanbaghi, commit 3be8b9e should fix this. Can you test and let us know? Thanks!

**Comment by aryanbaghi** [comment]
Hi @leandrotoledo issue with `switch_inline_query=''` fixed but issue with `switch_inline_query=None` still exists.

**Comment by leandrotoledo** [comment]
Hi @aryanbaghi, setting `switch_inline_query=None` to get and JSON `switch_inline_query: ''` seems like a violation of the design of this library. I'd say to keep using `switch_inline_query=''` to have an empty string argument, like we do for `setWebhook(webhook_url='')` and so on. Changing its behavior would be hard to determinate when you don't want this set at all as well (as `__init__` sets all kwargs to None as default).

So, this is what we have:
```
# Sends string to Telegram Servers
>>> InlineKeyboardButton('text', switch_inline_query='string').to_dict()
{'text': 'text', 'switch_inline_query': 'string'}
```

```
# Sends empty string to Telegram Servers
>>> InlineKeyboardButton('text', switch_inline_query='').to_dict()
{'text': 'text', 'switch_inline_query': ''}
```

```
# Doesn't send var to Telegram Servers
>>> InlineKeyboardButton('text', switch_inline_query=None).to_dict()
{'text': 'text'}
```

**Comment by aryanbaghi** [comment]
@leandrotoledo I think I am miss understood. Your third example not work. For example:
```
keyboard = telegram.InlineKeyboardMarkup(
        inline_keyboard=[
            [
                 telegram.InlineKeyboardButton(text=u'Add'),
                 telegram.InlineKeyboardButton(text=u'Edit'),
            ],
        ],
)
print "1"
bot.sendMessage(
        chat_id=user.chat_id,
        text=u'Some text',
        reply_markup=keyboard
)
print "2"
```
after running code, 1 is printed but 2 is not printed and message not sent, and this happen only when switch_inline_query is None. According to telegram doc when it is none it should show button without any switch action.

**Comment by leandrotoledo** [comment]
@aryanbaghi ah, I get it now, So it defaults to ''

```
self.switch_inline_query = kwargs.get('switch_inline_query', '')
```

I'll push the fix shortly.

**Comment by leandrotoledo** [comment]
@aryanbaghi could you pull 263310b and test it again, please?

Thanks!

**Comment by aryanbaghi** [comment]
@leandrotoledo I think [`3be8b9e`](https://github.com/python-telegram-bot/python-telegram-bot/commit/3be8b9ecb99bae1f608242760beaab129e5d5c65) was correct  and default value for switch_inline_query should be None. Correct manner of button with `switch_inline_query=None` is showing inline button that not switch chat. But when we try to send it with `switch_inline_query=None` Telegram server do not accept message. So I think may be we have another bug elsewhere.

Thanks

**Comment by leandrotoledo** [comment]
@aryanbaghi Can you post a piece of your code again so I can give it a try?

**Comment by aryanbaghi** [comment]
```
keyboard = telegram.InlineKeyboardMarkup(
        inline_keyboard=[
            [telegram.InlineKeyboardButton(text=u'Get random music')],
            [telegram.InlineKeyboardButton(text=u'Send music to friends', switch_inline_query='')],
        ],
)
bot.sendMessage(
    chat_id=user.chat_id,
    text=u'Some text',
    reply_markup=keyboard
)
```
This code should have result like this screen shot I get from telegram site.
![ea6163411c7eb4f4dc](https://cloud.githubusercontent.com/assets/4646461/14712290/b8fcf528-07f1-11e6-8635-df5985f13f63.png)

**Comment by leandrotoledo** [comment]
@aryanbaghi Ah, that's because you are missing `callback_data` in the first button.

Pull the reverted commit and test the snippet below:

```
keyboard = telegram.InlineKeyboardMarkup(
    [[
        telegram.InlineKeyboardButton(text=u'Get random music',
                                      callback_data='random'),
        telegram.InlineKeyboardButton(text=u'Send music to friends',
                                      switch_inline_query='')
    ]],
)
bot.sendMessage(
    chat_id=chat_id,
    text=u'Some text',
    reply_markup=keyboard
)
```

**Comment by aryanbaghi** [comment]
@leandrotoledo sorry for mistake. So first bug fixed :)
I think it is good to check if both callback_data and switch_inline_query is None set some value to callback_data. Any way thanks.
